version: '3'

services:
  web:
    build: .
    working_dir: /myapp
    command: gatsby develop --host=0.0.0.0
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

volumes:
  node_modules:
